### ISSUE TITLE
Error reported! Report ID: d0304986

### ISSUE THREAD

**Issue by ramxdier** [jely2002/youtube-dl-gui#103]
![Sin título](https://user-images.githubusercontent.com/73794321/121612672-77a50600-ca20-11eb-8a20-0ceb41b6c052.png)

https://www.funimation.com/es/shows/cowboy-bebop/stray-dog-strut/

**Comment by jely2002** [comment]
Hi ramxdier,

I have taken a look at your error report on my end. It looks like the extractor for funimation.com is currently broken. This is not something I can fix. Because the error originates from youtube-dl and I'm not a developer of youtube-dl.

It may get fixed in the future but there is no guarantee that the peeps over at youtube-dl will fix it.

Thanks for understanding.

**Comment by jely2002** [comment]
I will however add a more descriptive error when an extractor error occurs. Telling the user that the extractor is broken.
