### ISSUE TITLE
Multithreaded Downloading

### ISSUE THREAD

**Issue by rugabunda** [jely2002/youtube-dl-gui#114]
**Is your feature request related to a problem? Please describe.**
Some videos, particularly social/political and other conscientious topics are being throttled by youtube, limited to about 50-200 KBPS outside, and sometimes even inside the browser. Here is (or was) an example video: https://www.youtube.com/watch?v=-YH0gn8P09M&t

It is a 5 gigabyte file, but it was throttled to only download at 80-200 kilobytes per second in youtube dl gui & 4k Downloader, that is my experience here from Canada (throttling on that particular video has been lifted since, at least, for me anyway).  Even in browser it was limited, you could not run faster than x2 speed without stuttering, even in the lowest resolution 240p, this on a 300 megabit connection. Whereas all other youtube videos I watched at that time did not have this throttle censor. I can download youtube videos at 30-40 megabytes per second.

I have seen a number of videos since then only able to download at 50-200 kilobytes per second.

**Describe the solution you'd like**

An option between 1-32 threads.

**Describe alternatives you've considered**
Eagleget used to work fine, used 32 threads, and was the fastest youtube downloader available. But that functionality is now broken. 

Thanks for your time.

**Comment by Thundros** [comment]
I second this! We NEED this!

**Comment by jely2002** [comment]
Hi rugabunda,

The download slowing down has to do with YouTube throttling youtube-dl on purpose it seems. There's nothing I can do to prevent this. More info about this can be found here: https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377

I could add multithreaded downloads, that requires me to use Aria2c. It however wouldn't fix this issue, as Aria2c can only be used to download m3u8 or Dash videos. Most popular videos on YouTube are not in this format. Besides, YouTube will block/ratelimit you way quicker if you open 32 connections to them instead of 1.

Because of all the above, I will not be adding multithreaded downloads at this time. Closing the issue for now.
