### ISSUE TITLE
Adding settings for auto update youtube-dl option

### ISSUE THREAD

**Issue by hsnfirdaus** [jely2002/youtube-dl-gui#12]
Hey, I want to make a suggestion. You should adding the option to update youtube-dl and ffmpeg binary automatically or not.

**Comment by jely2002** [comment]
Hi there! I would be able to add this setting, however I see no reason why I should add this. What reason is there to disable auto updating the youtube-dl binary? Ffmpeg never gets updated, because all versions are backwards compatible so there is no need.
If there would be a valid use case for this setting I will add this, but right now I can't think of one.

**Comment by jely2002** [comment]
After some more consideration I will be implementing this along with some more settings! I expect to release this feature in v1.8.0.

**Comment by hsnfirdaus** [comment]
Thank you so much....
