### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by RedcatPhoenix2** [jely2002/youtube-dl-gui#124]
**Is your feature request related to a problem? Please describe.**
We need to search stuff as we are trying to get old unlisted videos back before the 7th

**Describe the solution you'd like**
A search engine

**Describe alternatives you've considered**
none

**Additional context**

**Comment by jely2002** [comment]
Hi there,


What do you mean by a search engine? Unlisted videos will never show up in any search (unless logged in), as they are unlisted for a reason.

If you mean adding a search engine to the URL bar. I won't add that because youtube has it's own search engine. 

If you have anymore questions feel free to ask.
Closing for now.
