### ISSUE TITLE
Original video thumbnail should also be embedded on the downloaded file

### ISSUE THREAD

**Issue by userhy388** [jely2002/youtube-dl-gui#127]
**Is your feature request related to a problem? Please describe.**
When I download a video, the thumbnail of the file is just the first frame of the video. 

**Describe the solution you'd like**
I think it's possible to extract the original thumbnail of the video from the source website then put that on the downloaded video or audio file.

**Comment by jely2002** [comment]
This app passes the `--embed-thumbnail` flag to youtube-dl. This means youtube-dl will embed the thumbnail that the extractor provides into the file. I have no control over how this happens, so this would be an issue for youtube-dl and not this app.
In other words, I can't change this behavior, youtube-dl needs to fix/change this.

Thank you for understanding.

**Comment by L0Lock** [comment]
AFAIK from my experience using youtube-dl CLI:
 - MP4 requires Atomic Parsley to write thumbnails
 - MKV works inconsistently. Sometimes thumbnails get embeded, sometimes not, I don't know why  
   I have a feeling it depends the codecs used since CLI almost always outputs  
   `ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.` when thumbnailing MKVs).

Anyway, maybe the solution at least for MP4 would be to either ship it with Open DL Gui or mention its need in the documentation.  
I personally use it, so thumbnails work for me as long as I have Aatomic Parsley registered in my environment path variables.

**Comment by jely2002** [comment]
Atomic Parsley is included on windows build, so this should work.  There is a log that you can access by clicking on the notebook icon on the right side of the video card. For even more logs you can open developer tools with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>.

**Comment by L0Lock** [comment]
Indeed, thanks for pointing that out.

I did some tests with a video where I can get the thumbnail correctly merged when using youtube-dl CLI alone but I can't when using OVD:

If I understand the logs correctly, it looks like it downloads video and audio steams separately and then combines them together as an MP4 or MKV.  
Is this youtube-dl doing all this by itself, or is this OVD ? In the later case, it may be the cause of thumbnails sometimes missing. But if it's youtube-dl... I'm sincerely confused as to why it behaves like this when used through OVD whereas it behaves normally when used manually via CLI.  
Sorry if I sound rude, I just want to understand how to get things working.

**Comment by libid0nes** [comment]
I confirm YouTube-DL CLI works as expected, and with the same conditions, YouTube-DL-GUI simply does not work.

**Comment by L0Lock** [comment]
Hello there!  
I was making myself a python script to automate some downloads and the `--embed-thumbnails` didn't have any effect. But adding the following made it work again:

`--postprocessor-args "-write_id3v1 1 -id3v2_version 3"`
