### ISSUE TITLE
Download multiple video at the same time

### ISSUE THREAD

**Issue by Maxime-p** [jely2002/youtube-dl-gui#17]
Is it possible to make the app download multiple video at the same time or download a whole playlist.

**Comment by jely2002** [comment]
The app can download a whole playlist or a chunk of a playlist.
Just enter a playlist url `youtube.com/playlist?list=PLlrExamplePlaylist` instead of a video url. 
Downloading multiple videos that are not in a playlist will not be supported, because it would require an entire redesign of the UI.

**Comment by Maxime-p** [comment]
not working for https://www.youtube.com/watch?v=<id>&list=<id>

**Comment by jely2002** [comment]
That is intentional behavior, if you want to download the whole playlist you have to click on the name to go to the playlist page and use that link. Lets say a user is watching a playlist and justs wants to download the video he is currently watching, then he uses the link you commented. The user would not want to download the whole playlist in the aforementioned case.
I hope this answers your questions!
