### ISSUE TITLE
When showing quality of video remove 60 or 30 from it.

### ISSUE THREAD

**Issue by clicky6** [jely2002/youtube-dl-gui#176]
When I click on + button and youtube-dl-gui shows which video quality to download Why does it shows 30 or 60 after video quality, (example - 144p30) Why does 30 need to be present?
It should do it like the YouTube does it YouTube doesn't shows 30 or 60 it only shows quality like 144p.
So change it and make it to only show quality not 30 or 60 after quality.

PRESENT DAY It shows video quality like this ,
![50](https://user-images.githubusercontent.com/89839714/132088995-9807a7ae-8db1-4e48-92c8-b86d0d2c9abb.png)

It should show it like
![100](https://user-images.githubusercontent.com/89839714/132089046-b71309d8-85ac-48d4-9f2b-85944bc4e3c2.png)

**Comment by EricE549X** [comment]
the number after the quality represents the frame rate of the video (30fps, 60fps, etc.). usually lower-quality files will be in a reduced frame rate since it's rare for those files to support 60fps.

**Comment by clicky6** [comment]
@EricE549X 
So It should be removed right.

**Comment by jely2002** [comment]
As Eric said, this shows the framerate of the video. This is important because it can influence the smoothness of the video and file size of the download. 

A video is essentially made up of images that change rapidly, so it looks like stuff is moving. How many times a new image is displayed per second is called the framerate, the more frames you show per second, the more smooth the video will appear.
But having to display more images/frames, means you will have to store more, thus making the filesize bigger.

Closing the issue as I will not be removing this handy piece of information from the format selector.

**Comment by clicky6** [comment]
But an option can be given in settings to turn it on or off.

**Comment by jely2002** [comment]
This setting would be bloat the settings menu, as the majority of people would not want to turn that off.
