### ISSUE TITLE
can't download Udemy courses using cookies 

### ISSUE THREAD

**Issue by MesterPerfect** [jely2002/youtube-dl-gui#181]
hi 
I can't download Udemy courses using cookies 
I used this tutorial to extract cookies from Udemy after logging in to it
https://github.com/jely2002/youtube-dl-gui/wiki/Tutorial:-Private-videos-&-playlists
But the program cannot download the course and gives a 403 error 
![error](https://i.imgur.com/SXY6bRV.jpg)

**Comment by jely2002** [comment]
Hi MesterPerfect,
I tried getting this to work with the youtube-dl command line. I was unable to make that work either, so I believe the issue lies with youtube-dl's extractor being broken. Not a whole lot I can do about that.

There are multiple [open issues](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+udemy+403) in the youtube-dl repo about this, but I'm afraid they will never get fixed.

Closing the issue as there isn't a whole lot I can do about this.
