### ISSUE TITLE
Support for downloading multiple videos at the same time in different formats

### ISSUE THREAD

**Issue by Mennaruuk** [jely2002/youtube-dl-gui#23]
**Is your feature request related to a problem? Please describe.**
I would like to know if support for downloading multiple videos at one time, rather than one video at a time, can be implemented in future releases.

**Describe the solution you'd like**
youtube-dl-gui would support pasting multiple links that would show up in a list. Then, the user can decide to download each in its own format. So maybe two of these videos the user would like to download as an MP4, while the other two can be downloaded as an M4A.

**Describe alternatives you've considered**
Vividl supports this already. But it's Windows-only. I think Tartube lets the user download all videos, but I'm not sure if they can specify different formats.

**Additional context**
Your app rocks, dude.

**Comment by jely2002** [comment]
Hi Mennaruuk,
I guess I could implement this, as I can see a use for it. Sadly it won't be any time soon, because I have to rewrite a large chunk of this app. Because of an issue with the format system (spaghetti code and stuff). I will keep this issue open as I really do want to implement it as soon as I can! Thanks for the additional context 😄

**Comment by Mennaruuk** [comment]
**_thank you!_** and omg this looks so pretty
![gui](https://user-images.githubusercontent.com/52135169/113435057-158cac80-93b0-11eb-8e9a-13f24006403e.png)
