### ISSUE TITLE
Virustotal detecting exe files as Trojan.Win32.BitCoinMiner.la

### ISSUE THREAD

**Issue by usernamebutexists** [jely2002/youtube-dl-gui#247]
Virustotal is detecting both exe setup as well as portable exe as bitcoinminer, i know it can be false positive as only one antivirus(Tencent) is detecting it. But still why ? I have never till now noticed any normal app (excluding apps used for crack/piracy/kmspico...) which i have used incl open source as yours getting detected as bitcoin miner. thats why i'm concerned. Please look into it asap
https://www.virustotal.com/gui/file/1b6bcdae389a5900feab446f9d68c8470f3feb1359e9ac3db4a7b999d0959fc2
https://www.virustotal.com/gui/file/bb0bbd7cd226b02d5069ff946d8ef15ecde19f06d42c03f9e33a087863a7c6f8

**Comment by jely2002** [comment]
Hi! I would like to clarify there is no bitcoin miner in my releases or source code, you can inspect the binaries and the source code yourself if you would like, nothing is obfuscated. The only antivirus detecting this is Tencent, a provider which I do not trust in the first place because of its geopolitical location and the use case of this application.
