### ISSUE TITLE
Button for updating supporting tools

### ISSUE THREAD

**Issue by syedmahm** [jely2002/youtube-dl-gui#25]
**Is your feature request related to a problem? Please describe.**
- No problem, just a feature request.
**Describe the solution you'd like**
- Is it possible to have a button in the Settings for updating the app itself or for all required tools like FFMPEG, youtube-dl, homebrew or whatever tools required for the youtube-dl-gui app? I am requesting specifically for the MacOS version. Thank you very much for this wonderful tool!
**Describe alternatives you've considered**
- N/A
**Additional context**
- N/A

**Comment by jely2002** [comment]
Hi syedmahm,
The app uses the following tools/binaries:
- youtube-dl
- ffmpeg

The app checks for an update of itself automatically when it gets launched. On MacOS it doesn't automatically update, but it does show a message with a link to download the update. The youtube-dl-binary gets auto-updated on every OS, when you launch the app. About ffmpeg, this binary is not auto updated. Since ffmpeg won't easily break, updating it is not really necessary.

Therefore i dont think this feature will make a great addition to youtube-dl.
Closing for now.

**Comment by syedmahm** [comment]
Thank you.

    On Tuesday, November 24, 2020, 3:16:46 PM MST, Jelle Glebbeek <notifications@github.com> wrote:  
 
 


Hi syedmahm,
The app uses the following tools/binaries:
   
   - youtube-dl
   - ffmpeg

The app checks for an update of itself automatically when it gets launched. On MacOS it doesn't automatically update, but it does show a message with a link to download the update. The youtube-dl-binary gets auto-updated on every OS, when you launch the app. About ffmpeg, this binary is not auto updated. Since ffmpeg won't easily break, updating it is not really necessary.

Therefore i dont think this feature will make a great addition to youtube-dl.
Closing for now.
