### ISSUE TITLE
Ver 2.4.0 Error! Unhandled error.

### ISSUE THREAD

**Issue by Asutarotte** [jely2002/youtube-dl-gui#258]
**Describe the bug**

**To Reproduce**
1. Paste video link
2. Click on +
3. Click download

**Expected behavior**
Video should be downloaded

**Screenshots**
![1](https://user-images.githubusercontent.com/49158310/146571927-d8485ba1-067c-489f-9b10-069162bbccc4.jpg)

**Additional info (please complete the following information):**
 - OS:Windows 10 64 bit
 - Application version:2.4.0
 - Application type :portable

**Additional context**
when i download video then it's error just like the picture.
i try to use ver 2.3.1,it can download but the speed it no more than 60~70KB.
May I ask where I got it wrong?

**Comment by Asutarotte** [comment]
Sorry,i found the question.
When i in settings choose Attempt to use output format:MP4,then it's will downlaod fail,and show Error! Unhandled error.
When i choose auto it's working normally,but the new question is the auto format is MKV,i can't change or choose MP4.

**Comment by itscaro** [comment]
@jely2002 Firstly I would like to thank you for this app.

The issue with MP4 is that when the video stream in MP4 is downloaded along with OPUS instead of M4A audio stream, so that the final merge fails.

The workaround is to choose in Settings:
![image](https://user-images.githubusercontent.com/266018/147155112-0544af90-914b-49c1-bb3b-77acb6f73ff2.png)
Then on each video choose the right combination of codecs, ie.
![image](https://user-images.githubusercontent.com/266018/147155182-095c9cbe-7145-40c8-b63e-fe3e5e6a5f14.png)

**Comment by jely2002** [comment]
Closing this issue as the corresponding merge request, containing the fix has been merged.
