### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly.

### ISSUE THREAD

**Issue by Raflos10** [jely2002/youtube-dl-gui#26]
**Describe the bug**
[36597:1201/235423.535598:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_YouTubqRI3It/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**To Reproduce**
1. run ./YouTube-Downloader-GUI-1.8.6.AppImage

**Expected behavior**
App opens

**Screenshots**

**Additional info (please complete the following information):**
 - OS: Debian 10 (Bullseye)
 - Application version 1.8.6 or 1.8.5

**Additional context**

**Comment by jely2002** [comment]
This has to do with debian not allowing sandboxed applications as non-root, because chrome is a sandbox the app will not open.
A temporary workaround is to use the `--no-sandbox` parameter when launching the app-image from terminal.
I will be taking a look to see if I can fix this without the workaround.

**Comment by jely2002** [comment]
I have added a way to implement the `--no-sandbox` parameter in the AppImage. Expect appImages to be working as normal in upcoming release 1.8.7.

**Comment by Raflos10** [comment]
Awesome! Looking forward to it. Thanks for the quality app.
