### ISSUE TITLE
how to build from source (for RaspberryPi)?

### ISSUE THREAD

**Issue by Itai-Nelken** [jely2002/youtube-dl-gui#31]
**Is your question related to a problem? Please describe.**
I wan't to build this app for my RaspberryPi (Linux armhf and arm64).

**Describe the question you have.**
what are the commands to build it?
git clone the repo and
```bash
npm install
npm run build
```
?

**Comment by jely2002** [comment]
Hi Itai-Nelken,

I have added a [section](https://github.com/jely2002/youtube-dl-gui#4-how-do-i-build-from-source) to the readme that describes how to build from source.

When I tried building the app on my RaspberryPi 4 (armv7l) it wasn't succesful. The app will most likely need patches to be made arm compatible. I will not add these required patches because my aim is not on supporting arm devices. Youtube-dl can be quite resource intensive and devices like a RaspberryPi do not have a lot of resources. But of course you are free to fiddle around with the app on arm, thats what open source is for!

I hope I've answered your question, let me know if you happen to have more questions.

**Comment by Itai-Nelken** [comment]
thanks! 
i usually use [youtubuddy](https://github.com/Botspot/youtubuddy), but your app is really nice because I can select the resolution each time.

also youtube-dl works perfectly fine on my pi4 4gb and doesn't use to much resources.

**Comment by norweeg** [comment]
> Hi Itai-Nelken,
> 
> I have added a [section](https://github.com/jely2002/youtube-dl-gui#4-how-do-i-build-from-source) to the readme that describes how to build from source.
> 
> When I tried building the app on my RaspberryPi 4 (armv7l) it wasn't succesful. The app will most likely need patches to be made arm compatible. I will not add these required patches because my aim is not on supporting arm devices. Youtube-dl can be quite resource intensive and devices like a RaspberryPi do not have a lot of resources. But of course you are free to fiddle around with the app on arm, thats what open source is for!
> 
> I hope I've answered your question, let me know if you happen to have more questions.

it builds just fine for me on my raspberry pi (aarch64).  Can you consider making an aarch64 linux appimage??
