### ISSUE TITLE
Metadata from video (description, artist, genre, ecc)

### ISSUE THREAD

**Issue by vincenzogianfelice** [jely2002/youtube-dl-gui#34]
Hi. I have recently been using this program and I immediately noticed the lack of more downloads at the same time and above all I did not find any option regarding the download of the video metadata. Is it possible to add this thing? it would be very useful (and not just me ...)

Thanks and sorry for my English

**Comment by jely2002** [comment]
Hi Vincenzo,

I am currently working on v2.0.0 of this app. This version will support multiple downloads at the same time.

Metadata will now get downloaded along with the video in v2.0.0 (see the commit reference above).
I have achieved this by adding the `--add-metadata` flag as described in the [ytdl documentation](https://github.com/ytdl-org/youtube-dl#post-processing-options).

V2.0.0 has an option to view some of the video metadata as well. Below a sneak peak of the multiple download system and the info/metadata modal.

![v2.0.0 sneakpeak](https://i.imgur.com/7zduXoU.png)

I hope I have answered your question and implemented the requested feature. Let me know if you happen to have another question.

**Comment by vincenzogianfelice** [comment]
thanks for your answer. First of all I wanted to ask you if this new feature (of metadata) could be selected by the user ... in the sense that the user decides when to download the metadata. Furthermore (in the metadata) are also contained the description, the genre of the video, etc .. in short, the cassiche things of a youtube video?

And finally I wanted to ask you other things, since surely in this case you will know more than me. I have tried many downloaders: the first is youtube-dl-gui and recently yours too. I tried to download the same video and after downloading it I compared the hash of the two files (the first file I downloaded with youtube-dl-gui, that of [mrs0m30n3](https://github.com/MrS0m30n3/youtube-dl-gui), while the second I downloaded with your tool), and the files they do not match, even if they are the same video and there are the same settings. Why does this happen? Does your tool (or more generally) **youtube-dl** apply conversions? And if so, how can I download a video in a "genuine" way (as it is) without any kind of conversion?

Thank you and sorry for my English!

**Comment by jely2002** [comment]
### What metadata gets included and can it be a setting?
The `--add-metadata` flag adds the video title and the video description as metadata. And some other data if youtube-dl can find it.
I guess I could add a setting  to toggle this behavior.
V2.0.0 does offer an option to download the view count, likes, etc as a seperate JSON file.

### Why are the hashes different?
If someone uploads a video to YouTube, it will transcode the video to all the possible video formats YouTube serves. After transcoding I believe the original gets discarded (not sure). When youtube-dl then downloads the video, it has multiple formats and files to choose from. For 720p and lower youtube serves the video and audio from one file. But starting from 1080p and above, YouTube serves video and audio from seperate files. After downloading these files, youtube-dl uses ffmpeg to merge the files together. In general YouTube has a webm and a mp4 version of all video files, sometimes YouTube even has different codecs. I think this may be causing the different hash values. One program might use the webm variants and the other might use the mp4 variants. The same applies to audio, YouTube serves webm audio as well as m4a audio. And some programs might write metadata or add subtitles, all these things contribute to a varying hash value. 


All available formats for a standard 1080p60 video:
![all available video formats](https://i.imgur.com/YSx51t6.png)

### Can one download the original video?
It is impossible to download the genuine uploaded video from YouTube using youtube-dl, because YouTube transcodes the video to the suiting codecs, resolutions and container formats.
If you want no conversion at all you would need to use the command line and not include ffmpeg so nothing gets converted.

Hope this looong answer was of interest to you 😄

**Comment by vincenzogianfelice** [comment]
First of all I have to congratulate you on the graphical interface. She's very beautiful!.
Regarding this:

> It is impossible to download the genuine uploaded video from YouTube using youtube-dl, because YouTube transcodes the video to the suiting codecs, resolutions and container formats.
> If you want no conversion at all you would need to use the command line and not include ffmpeg so nothing gets converted.
> 
> Hope this looong answer was of interest to you

But shouldn't these tools be just wrappers for the youtube-dl tool? In this case, why is it not possible to download without any conversion also from your tool (for example)?

And one more thing ... if I download it without conversion, what is the format of the video?

**Comment by jely2002** [comment]
My tool applies NO additional conversion. Youtube-dl itself merges the audio and video together so it becomes one file. 
And if the `--recode-video` argument gets passed, youtube-dl will use ffmpeg to recode the video to the specified format. My tool does not convert anything other than the merging (and sometimes recoding) that youtube-dl does.

I could add a setting to v2.0.0 that will allow you to keep the unmerged files. This way when you download a video that needs to be merged you will end up with the merged file and the seperate files downloaded. Is that something you would be interested in?

**Comment by vincenzogianfelice** [comment]
> I could add a setting to v2.0.0 that will allow you to keep the unmerged files. This way when you download a video that needs to be merged you will end up with the merged file and the seperate files downloaded. Is that something you would be interested in?

Would be very nice! Thank you.
Indeed, I would say (since it can be useful to many, not just me) to leave the "intro page" (as soon as you open the program) as it is and to put all the "niche" options in the settings (via flag) so a more experienced user can easily set what he wants. I do not know if you understood. Furthermore, if it is possible (since most of them don't and take for granted the fact that they "know" everything about youtube-dl) to create a manual for each single setting of the tool (which would then be the youtube-dl options ) in order to facilitate their understanding.

**Comment by jely2002** [comment]
> So it would be a kind of muxing what youtube-dl does (in merging audio and video files, without conversion)?

Yes that is exactly what it does.

> Would be very nice! Thank you.

Great I will implement it then.

>  create a manual for each single setting of the tool

Great idea, I will make a wiki page with explanations of all settings.

> and to put all the "niche" options in the settings

The settings menu in v2.0.0 looks like this. All the niche options can be added to the advanced section.

![the v2 settings menu](https://i.imgur.com/yu9x8Cw.png)

Hope everything is resolved and answered now!

**Comment by vincenzogianfelice** [comment]
Yes!..Perfect.

> The settings menu in v2.0.0 looks like this. All the niche options can be added to the advanced section.

Obviously, in this section (advanced settings) the more options you enter the better ;)

Thansks
