### ISSUE TITLE
MKV Container

### ISSUE THREAD

**Issue by swanknight** [jely2002/youtube-dl-gui#40]
It would be nice if there was an option to choose the container. 

It seems that by default it uses MP4 which is not ideal when subtitles are involved, I would prefer to use MKV in these cases since it's more flexible.

**Comment by jely2002** [comment]
Hi swanknight,

It really depends on your use case if you would rather want a mp4 or a mkv. For example the adobe suite has almost no support for mkv's. I have now added a setting to v2.0.0 (upcoming version) that allows you to select what container the video should get downloaded to.

![screenshot of the setting](https://i.imgur.com/GKZD9pM.png)

It will not always work, because some videos just can't be downloaded into mkv or mp4. But it does work most of the time.
Of course you can always use something like [handbrake](https://handbrake.fr/) to transcode the downloaded videos.

Let me know if you have any questions or requests.
