### ISSUE TITLE
Thumbnail don't change when using playlist feature

### ISSUE THREAD

**Issue by irae** [jely2002/youtube-dl-gui#41]
**Describe the bug**
I expected the images to change. The files change, but the images don't. See gif, should say it all.

YouTube-Downloader-GUI-1.8.7.dmg

![Screen Recording 2021-03-27 at 18 48 23](https://user-images.githubusercontent.com/98254/112735972-0fb94600-8f2e-11eb-9c44-234f8dcf6adc.gif)

**Comment by jely2002** [comment]
Hi irea,

I understand this is not what you expect when you change the videos that get downloaded. However I won't be fixing this bug, because v2.0.0 is coming out in 5 days. This version features a completely new design where this bug does not exist.

Thanks for bringing this bug to my attention.
If you have any more questions please let me know, closing the issue for now.

**Comment by irae** [comment]
Thanks for the very kind reply. I was kinda in a hurry, I use the command line myself, my mom needed a GUI and I quickly filed the bug while I was still taking with her on the phone. Sorry if it looked rude. I was actually thinking about a PR later this week, as it sounds an easy fix. 

Thanks for the amazing software, and good luck with 2.0
