### ISSUE TITLE
Other File Formats Supported

### ISSUE THREAD

**Issue by Libror** [jely2002/youtube-dl-gui#43]
**Is your feature request related to a problem? Please describe.**
When I want to download a video and import it into Premiere Pro, it says that VK09 (or something like that) is not supported.

**Describe the solution you'd like**
Could we have an option to change the codecs?

**Describe alternatives you've considered**
Other file format?

**Comment by jely2002** [comment]
Hi Libror,

I personally use this app to download videos so I can use them in After Effects or Premiere Pro and have never experienced an issue like this. If you could provide me with some more info to troubleshoot the problem it would be appreciated. 

One thing you may try in advance is setting the `Attempt to use output format:` setting to `mp4`. This makes youtube-dl-gui attempt to download mp4 files from YouTube, these files are usually encoded in AVC1 and not VP9 (the non working codec).

You could also transcode the downloaded files with something like [handbrake](https://handbrake.fr/).

Additional info I could use:
- Premiere Pro version
- App version
- What video did you try to download?
- With what settings did you download this video?

As a last note, it is not that simple to just add a setting to select the encoding. This is because different services and even videos  have different encodings available.

**Comment by L0Lock** [comment]
Hi there,

I also download my videos for video editing via youtube-dlg, but I also need to download some tuff for other purposes in which case I'd prefer downloading the other steams that are better quality - which isn't supported for now.

Could it be possible to have an option to download the vp9/opus streams when available ? That would make my day!
Also, how about a "video only" option too? I often need that too.

Sidenote:  
If you want to switch your files from mkv to mp4, you can do this by copying the streams instead of re-encoding , which avoids quality loss and is much faster. I think in handbrake it's done by choosing the "passthrough" codecs, you can also do this via ffmpeg quite easily:

```bash
ffmpeg -i "input.mkv" -c copy -map 0 "output.mp4"
```

**Comment by jely2002** [comment]
Hi L0Lock,

> how about a "video only" option too? I often need that too.

Great idea to have an option that only downloads the video without the audio. I will be adding this as I can see a usecase for this.

> Could it be possible to have an option to download the vp9/opus streams when available ?

I will have to think about adding an option to select certain codecs, because the format system is currently not able to show and select different encodings. If I were to add this I would have to consider how to fit it into the UI as well. All in all I don't think I will be adding this feature anytime soon, if I will be adding it at all.

**Comment by jely2002** [comment]
The video only option has been implemented and will release in v2.1.0.
Selecting multiple codecs will eventually be implemented too (see #47).

Closing this issue for now.
