### ISSUE TITLE
Automatic updating youtube-dl

### ISSUE THREAD

**Issue by donmega** [jely2002/youtube-dl-gui#5]
Hi,

Is it possible to automatic update the youtube-dl binary? I am using a Mac.
Thank you!

PS: Keep up the great work!

**Comment by jely2002** [comment]
Hi donmega,

If all is working correctly the youtube-dl binary should already auto-update on all platforms.
The app itself can only be auto-updated on windows because I currently do not have access to a code signing certificate for MacOS.

Let me know if this answer has helped, if it did I will close the issue.

**Comment by jely2002** [comment]
Due to an expired certificate on the site of youtube-dl, the automatic binary updater didn't work. This is now fixed in c34e86e, and will be published in the upcoming version 1.6.

**Comment by jely2002** [comment]
Update 1.6 will roll out in 1-2 days, closing this for now.
