### ISSUE TITLE
custom amount for split playlist

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#61]
can u add a feature in which u can add your custom amount for when to split playlists. this would be useful for changing settings like video quality and caption on/off in one click rather than going to each vid and changing it.
this is similar to my request in #52 
![image](https://user-images.githubusercontent.com/83282129/118356988-d04fc300-b588-11eb-84fb-779ac7f3de1c.png)

**Comment by jely2002** [comment]
Hi thaynos,
If you wish to not split a video you can just set it to 'never split'. And it will not split any playlists. Then if you do want  a playlist to be split you can select the matching 'less than x videos'. Playlists bigger than 200 can never be split because of performance reasons.

I see no big advantage to the option you proposed and will be closing the issue.
