### ISSUE TITLE
duplicate video file names

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#63]
whenever i download a vidoe that has already been downloaded before instead of the usual adding "(1)" at the end it jsut downgrade the quality. it would be better to just add (1) with same download quality.

**Comment by jely2002** [comment]
When you download a video that has already been downloaded it completes immediately because youtube-dl knows the file already exists. When you select another quality it will overwrite the file with the selected (lower) quality. To me this is expected behavior, since it is the default behavior of youtube-dl. I will not be fixing this as this behavior is expected.

**Comment by thaynos** [comment]
but im 100% sure it was always set at 1080p60? i never do anything aprt from that value

**Comment by thaynos** [comment]
but im 100% sure it was always set at 1080p60? i never do anything aprt from that value

**Comment by jely2002** [comment]
In that case it has to do with youtube-dl doing weird stuff and not my GUI.
