### ISSUE TITLE
Progress bar support

### ISSUE THREAD

**Issue by harkaj33** [jely2002/youtube-dl-gui#7]
Progress bar support that lets us know of the status of the video download. Currently I'm just getting a yellow message that I might be downloading a larger file, and yes I'm downloading a 12 GB file so it would be nice to have an indication to see if it actually does anything...

**Comment by jely2002** [comment]
Hi harkaj33,

When developing this app I tried adding a progress bar. Sadly it is really hard/near impossible for me to add a progress bar to single videos. Because the binary I use doesn't provide me with the progress it is making while downloading.

I tried doing it another way, by getting the total file size. And how much has already been downloaded, sadly this also didn't quite work out. But I will look into it another time for you, and see if I can add a progress bar.

**Comment by jely2002** [comment]
A progress bar indicating the status of the download has now been added in version 1.6.4.
Closing the issue!
