### ISSUE TITLE
system cannot find path specified

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#73]
tysm for making error reporting ezier
although idk whats wrong as im utterly illiterate in coding except for basic html and python.
also does the submit report button actually report the issue to you?
![image](https://user-images.githubusercontent.com/83282129/119182390-e3302f00-ba83-11eb-989f-fad01cbed37f.png)

**Comment by thaynos** [comment]
btw this bug goes away if i close and reopen the app.

**Comment by jely2002** [comment]
I already noticed some people reporting this issue. At the top it says, please report. When you report it it sends this monster of an error dump to me and I can analyse it. I have already found a _possible_ fix for this problem and it will be released next version.

To clarify some more, if you report the error it will get send to me. It will send the error code, the error message, the url, the quality setting, the version and the operating system.

Closing this issue as this bug was already resolved.
