### ISSUE TITLE
icon missing from taskbar

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#74]
![image](https://user-images.githubusercontent.com/83282129/119186717-8768a480-ba89-11eb-81d0-f9d8f82f38a9.png)

**Comment by jely2002** [comment]
Hi thaynos,
I am not  able to reproduce this issue, and have never seen it happen before. If this happens every single time you can try reinstalling or downloading the portable version again. Otherwise a simple restart of the app should fix it.

Closing this issue as it appears to be very rare and is most likely an unzipping error if you use the portable version.

**Comment by thaynos** [comment]
it works after reopening it
