### ISSUE TITLE
tweaks to website

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#78]
![image](https://user-images.githubusercontent.com/83282129/119217029-887cee80-bae8-11eb-9b4b-4fc95e2b16ac.png)
over here could you say app also works without these but works best with them 
cause they do work without them as im doing that rn
reason for change is that it might be a turn off for people like me who dont have admin perms
if i saw this when downloading i wouldnt have downloaded
also please dont make it compulsory to download the dependencies as in you cant open app without downloading as some apps do that
i would rather have a buggy app than no app at all
also make all links open in a new tab rather than in the same tab
![image](https://user-images.githubusercontent.com/83282129/119217129-1bb62400-bae9-11eb-8d99-9d2bbc33704a.png)
![image](https://user-images.githubusercontent.com/83282129/119217209-b6166780-bae9-11eb-996c-56d8999bfba9.png)
also make the different versions page as buttons rather than redrecting to the github page. you could also add a download from github button too ig.
![image](https://user-images.githubusercontent.com/83282129/119217185-81a2ab80-bae9-11eb-8ad3-f91b536e0d11.png)

**Comment by jely2002** [comment]
> over here could you say app also works without these but works best with them
cause they do work without them as im doing that rn

In my testing the app NEVER works without these dependencies, so that is what will remain on the page. I think you are experiencing those bugs because of something else. Not that missing depend, because without the depend it will never work.

> also make all links open in a new tab rather than in the same tab

Will change this, must have forgotten to add target="_blank", oops.

> also make the different versions page as buttons rather than redrecting to the github page

If I do that I have to update that page every time I add a new version. Right now it gets the latest version from GitHub so I don't  need to update the site everytime. I think if a user really wants another version they know how to navigate GitHub.

> you could also add a download from github button too ig.

The download button already downloads the binary from GitHub, it's just all behind the scenes and not shown to the user.

**Comment by jely2002** [comment]
> also please dont make it compulsory to download the dependencies as in you cant open app without downloading as some apps do that

I will never force the user to download something else if they want to install/use my app. The installer asks if you want to install it, it doesn't force you to install it. And if you don't have the depend it will just tell you in an error.

**Comment by thaynos** [comment]
> In my testing the app NEVER works without these dependencies, so that is what will remain on the page. I think you are experiencing those bugs because of something else. Not that missing depend, because without the depend it will never work.
oh ok i assumed that its cuz i dont have the dependency alrdy installed that why the bug happens
