### ISSUE TITLE
seperate window for queue

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#81]
can there be a seperate window for queue?
this might be helpful for playlist downloads
so that we can see individual download completion
also so we can add videos later on
there could also be an option to change settings of individual videos if download has not started yet
something like this
![image](https://user-images.githubusercontent.com/83282129/119217844-0e4f6880-baee-11eb-8207-86ad6923c750.png)
btw the app im showing is handbrake

**Comment by jely2002** [comment]
> can there be a seperate window for queue?

This would require a complete redesign of the UI, which I will not be doing.

> there could also be an option to change settings of individual videos if download has not started yet

To you they appear as unstarted, but in the background they have been started and it impossible to change the settings. Because they have already been handed off to youtube-dl.

> so that we can see individual download completion

This is already possible if you split your playlists into single videos using the 'split playlist when' setting.

Closing the issue as I don't see a need for this. Thanks for understanding.
