### ISSUE TITLE
Downloading clips

### ISSUE THREAD

**Issue by agansito** [jely2002/youtube-dl-gui#91]
Hi, I'm a bit new to all this stuff but, is there a way to select just a portion of a video to download, even if it's by writing code? I remember it was an option with youtube-dl, but I can't seem to find an option for it on this program.

**Comment by jely2002** [comment]
Hi agansito,

I investigated a little, and it seems like youtube-dl does not have a built-in function for this. But I could still add this to the app by using the already embedded ffmpeg binary. I won't be adding it anytime soon however, because I don't have a lot of time on my hands. But it would be great if users could only download parts of a video.

**Comment by jely2002** [comment]
After researching online, it appears that this will be hard to implement. Since youtube-dl does not have native support for it. And I don't want to mess with FFMpeg. As that is not the focus of the app.

Because of this I will be dropping this feature request.

If you really need clips you will sadly have to resort to video editing software, or handbrake.
