### ISSUE TITLE
good job on the regular updates!

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#92]
great work dude! i've said this before but this app is amazing and bug fixes are really quick! thx for all your hard work, keep it up and you're gonna have more stars than youtube-dl someday 😤

**Comment by jely2002** [comment]
Hey thanks a lot! 😄 
I really appreciate it and hope I can find the time to keep developing this app. Because I love creating stuff and helping people in the process.

For next time, if you want to reach out to me about anything other than a real issue or a question please don't use issues. I have discord, e-mail and twitter (these can be found on my [site](https://jelleglebbeek.com)). Using the issues only for real issues and questions keeps everything organised and I like it that way.

**Comment by thaynos** [comment]
alr sorry for the trouble ill try not to disturb ur organized life :D

**Comment by thaynos** [comment]
cant say the same for myself tho lol
